- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - git

- name: Start and enable the web server
  service:
    name: httpd
    state: started
    enabled: yes
