- name: Pull latest code from repository
  git:
    repo: 'https://github.com/example/app.git'
    dest: /var/www/html/app

- name: Restart web service
  service:
    name: httpd
    state: restarted
